export const TOGGLE_NOTIFICATION = 'TOGGLE_NOTIFICATION';
export const CHANGE_VERTICAL_NOTIFICATION = 'CHANGE_VERTICAL_NOTIFICATION';
export const CHANGE_HORIZONTAL_NOTIFICATION = 'CHANGE_HORIZONTAL_NOTIFICATION';
export const CHANGE_TYPE_NOTIFICATION = 'CHANGE_TYPE_NOTIFICATION';
